"""Report generator — produces comparative scorecards."""
from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path

from .models import BenchmarkRun


def _bar(pct: float, width: int = 20) -> str:
    """ASCII progress bar."""
    filled = int(pct * width)
    return "█" * filled + "░" * (width - filled)


def _score_color(score: float) -> str:
    if score >= 0.8:
        return "🟢"
    elif score >= 0.6:
        return "🟡"
    elif score >= 0.4:
        return "🟠"
    return "🔴"


def generate_markdown(run: BenchmarkRun) -> str:
    """Generate a comparative scorecard in Markdown."""
    lines = []
    lines.append(f"# Fregate Benchmark — `{run.run_id}`")
    lines.append(f"")
    lines.append(f"> Generated {datetime.now().strftime('%Y-%m-%d %H:%M')} · "
                 f"{len(run.scorecards)} models · {len(run.tasks_used)} tests")
    lines.append(f"")

    # ── Global ranking ──
    lines.append("## Global Ranking")
    lines.append("")
    lines.append("| Rank | Model | Provider | Score | Latency | Tokens/s | Errors |")
    lines.append("|------|-------|----------|-------|---------|----------|--------|")

    sorted_cards = sorted(run.scorecards, key=lambda c: c.avg_score, reverse=True)
    for i, card in enumerate(sorted_cards, 1):
        medal = ["🥇", "🥈", "🥉"][i - 1] if i <= 3 else f"{i}."
        lines.append(
            f"| {medal} | **{card.model}** | {card.provider} | "
            f"{_score_color(card.avg_score)} {card.avg_score:.0%} | "
            f"{card.avg_latency_ms:.0f}ms | "
            f"{card.avg_tokens_per_sec:.0f} t/s | "
            f"{card.error_count} |"
        )

    lines.append("")

    # ── Category breakdown ──
    if sorted_cards:
        all_cats = set()
        for card in sorted_cards:
            all_cats.update(card.score_by_category().keys())

        if all_cats:
            lines.append("## Scores by Category")
            lines.append("")

            header = "| Model |"
            sep = "|-------|"
            for cat in sorted(all_cats):
                emoji = {"code": "💻", "french": "🇫🇷", "reasoning": "🧠", "tools": "🔧", "features": "⚡"}.get(cat, "📋")
                header += f" {emoji} {cat} |"
                sep += "--------|"
            lines.append(header)
            lines.append(sep)

            for card in sorted_cards:
                row = f"| **{card.model}** |"
                cat_scores = card.score_by_category()
                for cat in sorted(all_cats):
                    s = cat_scores.get(cat, 0)
                    row += f" {_score_color(s)} {s:.0%} |"
                lines.append(row)

            lines.append("")

    # ── Detailed results per test ──
    lines.append("## Detailed Results")
    lines.append("")

    # Group by test
    tests: dict[str, list] = {}
    for card in sorted_cards:
        for r in card.results:
            tests.setdefault(r.test_id, []).append(r)

    for test_id, results in sorted(tests.items()):
        lines.append(f"### `{test_id}`")
        lines.append("")
        lines.append("| Model | Score | Latency | Tokens/s | Notes |")
        lines.append("|-------|-------|---------|----------|-------|")
        for r in sorted(results, key=lambda x: x.score, reverse=True):
            lines.append(
                f"| {r.model} | {_score_color(r.score)} {r.score:.0%} | "
                f"{r.latency_ms:.0f}ms | {r.tokens_per_sec:.0f} t/s | "
                f"{r.notes[:80]} |"
            )
        lines.append("")

    # ── Footer ──
    lines.append("---")
    lines.append(f"*Generated by [Fregate](https://github.com/m4rv4x/fregate) v2.0*")

    return "\n".join(lines)


def generate_json(run: BenchmarkRun) -> str:
    """Generate JSON report."""
    data = {
        "run_id": run.run_id,
        "timestamp": run.timestamp,
        "models": [],
    }
    for card in run.scorecards:
        model_data = {
            "model": card.model,
            "provider": card.provider,
            "avg_score": round(card.avg_score, 4),
            "avg_latency_ms": round(card.avg_latency_ms, 1),
            "avg_tokens_per_sec": round(card.avg_tokens_per_sec, 1),
            "error_count": card.error_count,
            "categories": card.score_by_category(),
            "results": [],
        }
        for r in card.results:
            model_data["results"].append({
                "test_id": r.test_id,
                "score": round(r.score, 4),
                "latency_ms": round(r.latency_ms, 1),
                "tokens_in": r.tokens_in,
                "tokens_out": r.tokens_out,
                "tokens_per_sec": round(r.tokens_per_sec, 1),
                "notes": r.notes,
                "error": r.error,
            })
        data["models"].append(model_data)

    return json.dumps(data, indent=2, ensure_ascii=False)


def save_report(run: BenchmarkRun, output_dir: str = "./reports", fmt: str = "both") -> list[str]:
    """Save reports to disk. Returns list of saved file paths."""
    outdir = Path(output_dir)
    outdir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    saved = []

    if fmt in ("markdown", "both"):
        md_path = outdir / f"fregate_{run.run_id}_{timestamp}.md"
        md_path.write_text(generate_markdown(run), encoding="utf-8")
        saved.append(str(md_path))

    if fmt in ("json", "both"):
        json_path = outdir / f"fregate_{run.run_id}_{timestamp}.json"
        json_path.write_text(generate_json(run), encoding="utf-8")
        saved.append(str(json_path))

    return saved
